#!/bin/sh

# compare .o files inside original .a files
# with the results of assembling the reconstructed source files.

# only ctime, printn, and printf differ,
# and all only in the symbol sections of the files.

# extract /usr/lib/libb.a
rm -rf libb
mkdir libb
(cd libb; ../tools/apout/apout ../fs/root/bin/ar x ../fs/usr/lib/libb.a)

# build and compare source/libb
cd source
for SRC in libb/*.s; do
    OBJ=`echo $SRC | sed 's/\.s$/.o/'`
    echo $SRC
    ../tools/apout/apout ../fs/root/bin/as $SRC
    mv a.out $OBJ
    diff $OBJ ../$OBJ
done
cd ..

# extract /usr/lib/bilib.a
rm -rf bilib
mkdir bilib
(cd bilib; ../tools/apout/apout ../fs/root/bin/ar x ../fs/usr/lib/bilib.a)

# build and compare source/bilib
cd source
for SRC in bilib/*.s; do
#    case $SRC in
#    bilib/b112.s|bilib/b113.s|bilib/b116.s|bilib/b12.s|bilib/b120.s|bilib/b13.s|bilib/b16.s|bilib/b20.s) continue;;
#    esac

    OBJ=`echo $SRC | sed 's/\.s$/.o/'`
    echo $SRC
    ../tools/apout/apout ../fs/root/bin/as $SRC
    if [ -f a.out ]; then
	mv a.out $OBJ
	if ! diff $OBJ ../$OBJ; then
	    echo $OBJ
	    od ../$OBJ
	    echo sources/$OBJ
	    od $OBJ
	fi
    else
	echo a.out not found
    fi
done
cd ..
